package com.example.blog.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

/**
 * blog
 * 
 * @author bianj
 * @version 1.0.0 2020-08-20
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Blog implements Serializable {


    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** title */
    private String title;

    /** summary */
    private String summary;

    /** content */
    private String content;

    /** publishDate */
    private Date publishDate;

    /** columnId */
    private Integer columnId;

    private Columnist columnist;

    /** views */
    private Integer views;

    /** tags */
    private String tags;

    /** comments */
    private String comments;

    /** blogImg */
    private String blogImg;

    /** blogState */
    private Integer blogState;

    /** admireState */
    private Integer admireState;

    /** commentState */
    private Integer commentState;

    /** recommendState */
    private Integer recommendState;

    /** reprintState */
    private Integer reprintState;

    /** createTime */
    private Date createTime;

    private Date updateTime;
    private Integer property;

}